application:
  port: 8000
database:
  database_name: "newsletter"
  host: "127.0.0.1"
  password: "password"
  port: 5432
  username: "postgres"
email_client:
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
