name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cd zero2prod && cargo fmt -- --check
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check linting
      run: cd zero2prod && cargo clippy -- -D warnings
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Audit security
      run: cd zero2prod && cargo audit
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cd zero2prod && cargo test --verbose
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run code coverage
      run: cargo install cargo-tarpaulin && cd zero2prod && cargo tarpaulin --ignore-tests
